name = "slack2postlab"
main = "dist/index.js"
compatibility_date = "2024-01-15"
account_id = "174a228859d1986be1c1831363b39bca"

[vars]
IMAGE_PATH = "public/images/"
JSON_PATH = "app/data/lab.json"
GITHUB_BRANCH = "main"

# KV Storage for thread management
[[kv_namespaces]]
binding = "slack2postlab_threads"
preview_id = "fa905cac5e6347c78d2dfefeb47acae2"
id = "6fab83d33d9f4a538d8ab1985d9fe429"

# Secrets should be set via CLI:
# wrangler secret put SLACK_BOT_TOKEN
# wrangler secret put SLACK_SIGNING_SECRET
# wrangler secret put GITHUB_TOKEN
# wrangler secret put GITHUB_OWNER
# wrangler secret put GITHUB_REPO

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
