name = "slack-to-github"
main = "dist/index.js"
compatibility_date = "2024-01-15"
account_id = "174a228859d1986be1c1831363b39bca"

[vars]
IMAGE_PATH = "mock-dir/public/images/"
JSON_PATH = "mock-dir/app/data/lab.json"
GITHUB_BRANCH = "develop"

# Secrets should be set via CLI:
# wrangler secret put SLACK_BOT_TOKEN
# wrangler secret put SLACK_SIGNING_SECRET
# wrangler secret put GITHUB_TOKEN
# wrangler secret put GITHUB_OWNER
# wrangler secret put GITHUB_REPO

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
