name = "slack-to-github"
main = "dist/index.js"
compatibility_date = "2024-01-15"

[vars]
IMAGE_PATH = "images/"
JSON_PATH = "data.json"
GITHUB_BRANCH = "main"

# Secrets should be set via CLI:
# wrangler secret put SLACK_BOT_TOKEN
# wrangler secret put SLACK_SIGNING_SECRET  
# wrangler secret put GITHUB_TOKEN
# wrangler secret put GITHUB_OWNER
# wrangler secret put GITHUB_REPO